import crypto from 'crypto'; import jwt from 'jsonwebtoken'; import {z} from 'zod'; import User from '../models/User.js'; import AppError from '../utils/AppError.js'; import {accessToken,refreshToken,cookieOptions} from '../utils/tokens.js';
const publicUser=u=>({id:u._id,name:u.name,email:u.email,role:u.role,avatar:u.avatar,phone:u.phone,isEmailVerified:u.isEmailVerified});
const issue=async(u,res)=>{const refresh=refreshToken(u);u.refreshTokens=[...(u.refreshTokens||[]).slice(-4),refresh];u.lastLogin=new Date();await u.save();res.cookie('refreshToken',refresh,{...cookieOptions,maxAge:7*864e5});return res.json({success:true,data:{user:publicUser(u),accessToken:accessToken(u)}})};
export const register=async(req,res)=>{const data=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8),role:z.enum(['admin','student','warden','accountant','security','parent','staff']).optional()}).parse(req.body);if(await User.exists({email:data.email}))throw new AppError('Email already registered',409);return issue(await User.create(data),res)};
export const login=async(req,res)=>{const {email,password}=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body);const u=await User.findOne({email}).select('+password');if(!u||!await u.comparePassword(password))throw new AppError('Invalid email or password',401);return issue(u,res)};
export const refresh=async(req,res)=>{const token=req.cookies.refreshToken;if(!token)throw new AppError('Refresh token required',401);try{const d=jwt.verify(token,process.env.JWT_REFRESH_SECRET);const u=await User.findById(d.sub);if(!u?.refreshTokens.includes(token))throw Error();u.refreshTokens=u.refreshTokens.filter(x=>x!==token);return issue(u,res)}catch{throw new AppError('Invalid refresh token',401)}};
export const logout=async(req,res)=>{const t=req.cookies.refreshToken;if(t)await User.updateOne({refreshTokens:t},{$pull:{refreshTokens:t}});res.clearCookie('refreshToken',cookieOptions).json({success:true});}; export const me=(req,res)=>res.json({success:true,data:publicUser(req.user)});
export const forgotPassword=async(req,res)=>{const u=await User.findOne({email:req.body.email});if(u){u.resetToken=crypto.randomUUID();u.resetExpires=Date.now()+3600000;await u.save();}res.json({success:true,message:'If the account exists, reset instructions were sent.'})};
export const resetPassword=async(req,res)=>{const u=await User.findOne({resetToken:req.body.token,resetExpires:{$gt:Date.now()}});if(!u)throw new AppError('Reset link is invalid or expired',400);u.password=z.string().min(8).parse(req.body.password);u.resetToken=undefined;await u.save();return issue(u,res)};
